DROP TABLE IF EXISTS trips CASCADE;
DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS trips_transportation_modes CASCADE;
DROP TABLE IF EXISTS canonical_trips CASCADE;
DROP TABLE IF EXISTS canonical_trips_relations CASCADE;
